### PR TITLE
Enable container image building

### PR DESCRIPTION
**Pull request by tibeer**
Container images should be build automatically. This still needs to be extended with a version, etc. Currently this is required, to be able to battle test this on Kubernetes and to create the first Helm-Charts.

Signed-off-by: Tim Beermann <beermann@osism.tech>

### CODE REVIEW

**Comment by tibeer** [comment]
@matfechner @ppkuschy Either I am blind or github actions is behaving absolutely strange. If you take a look at the details of one of the build-jobs, step "Build container image" it states:

```
+ BUILD_OPTS='--file compose/Dockerfile.app'
++ date --rfc-3339=ns
scripts/build.sh: line 15: date: command not found
+ CREATED=
+ DOCKER_REGISTRY=***
++ git rev-parse HEAD
scripts/build.sh: line 17: git: command not found
```
I have no clue why this is not working. Do you have an idea?

**Comment by ppkuschy** [comment]
> @matfechner @ppkuschy Either I am blind or github actions is behaving absolutely strange. If you take a look at the details of one of the build-jobs, step "Build container image" it states:
> scripts/build.sh: line 15: date: command not found
> scripts/build.sh: line 17: git: command not found

Just an educated guess but maybe PATH environment is not setup correctly?
Maybe try adding
`export PATH=$PATH:/usr/bin`
to the scripts and try again.

**Comment by tibeer** [comment]
> > @matfechner @ppkuschy Either I am blind or github actions is behaving absolutely strange. If you take a look at the details of one of the build-jobs, step "Build container image" it states:
> > scripts/build.sh: line 15: date: command not found
> > scripts/build.sh: line 17: git: command not found
> 
> Just an educated guess but maybe PATH environment is not setup correctly? Maybe try adding `export PATH=$PATH:/usr/bin` to the scripts and try again.

Awesome! Not quite the problems solution, but I noticed that I indeed named a variable "PATH". Bad idea...

**Review by ppkuschy — APPROVED** [review]
@tibeer LGTM

**Pull request merged**
